# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{uploadify}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adeptware, Inc."]
  s.date = %q{2010-02-04}
  s.description = %q{Adds multi-file upload support to your Rails application using Uploadify, a JQuery plugin.}
  s.email = %q{contact@adeptware.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "generators/uploadify/templates/uploadify/cancel.png",
     "generators/uploadify/templates/uploadify/expressInstall.swf",
     "generators/uploadify/templates/uploadify/jquery-1.3.2.min.js",
     "generators/uploadify/templates/uploadify/jquery.uploadify.v2.1.0.js",
     "generators/uploadify/templates/uploadify/jquery.uploadify.v2.1.0.min.js",
     "generators/uploadify/templates/uploadify/swfobject.js",
     "generators/uploadify/templates/uploadify/uploadify.allglyphs.swf",
     "generators/uploadify/templates/uploadify/uploadify.css",
     "generators/uploadify/templates/uploadify/uploadify.fla",
     "generators/uploadify/templates/uploadify/uploadify.swf",
     "generators/uploadify/uploadify_generator.rb",
     "lib/flash_session_cookie_middleware.rb",
     "lib/uploadify.rb",
     "uploadify.gemspec"
  ]
  s.homepage = %q{http://github.com/adeptware/uploadify}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Adds multi-file upload support to your Rails app.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

